### ISSUE TITLE
Ayat missing (screenshot)

### ISSUE THREAD

**Issue by najesoul** [kiamazi/borhan#1]
![Screenshot from 2021-05-10 17-00-14](https://user-images.githubusercontent.com/83972252/117689677-eb4dbc00-b1b1-11eb-95cf-fcb74b43b29d.png)

**Comment by kiamazi** [comment]
tnx for report bug, fixed in next version!

**Comment by kiamazi** [comment]
fixed in v1.4.1

**Comment by kiamazi** [comment]
fix in patch 1.4.4
